### ISSUE TITLE
终端运行node app.js后长时间无法应

### ISSUE THREAD

**Issue by BMWM4C** [zimo493/WeChatPush#2]
如题，运行后长时间无反应

**Comment by zimo493** [comment]
是因为开启了定时执行哦，如果希望立刻执行一次请把下面的这行代码注释解开

**Comment by zimo493** [comment]
是因为开启了定时执行，如果希望立即执行一次则需要把下面的这行代码解开哦
`// templateMessageSend(); // 第一次执行程序时会推送一次消息`
